version: '3'
services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: ./docker/src/php/Dockerfile
    image: forum-php
    volumes:
      - ../index.php:/usr/share/nginx/html/index.php
      - ../forum:/usr/share/nginx/html/forum
      - ../status:/usr/share/nginx/html/status
    depends_on:
      - db
    tty: true

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
    tty: true

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpass
    ports:
      - 4040:80
    tty: true