version: '3'
services:
  app:
    container_name: app
    build:
      context: ..
      dockerfile: ./docker/src/php/Dockerfile
    ports:
      - 8000:8000
    # volumes:
    #   - ..:/var/www/forum
    depends_on:
      - db
    tty: true

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      # - .:/var/www
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
    tty: true

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: forum
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # volumes:
    #   - ./docker/db/data:/var/lib/mysql
    #   - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #   - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    tty: true
